In [40]:
import pandas as pd

# Load Dataset

In [41]:
df = pd.read_csv("tops.csv")

# Explore Dataset

In [42]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18614510,Oxolloxo,Women Blue Crepe Blouson Crop Top,0.0,0,2299.0,73.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,M/S███PA ███ARE█████████E L███████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,C-1███ 1S███LOO█████████3No███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
1,18972586,MALHAAR,Yellow & Red Geometric Print Mandarin Collar C...,0.0,0,3329.0,79.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""S"",""value"":""35.0in"",""value_name"":""To...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
2,18937628,her by invictus,Printed A-Line Top,4.2,29,1398.0,66.0,"""₹475.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18937628_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
3,18972622,MALHAAR,Green Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
4,18979466,KiddoPanti,White & Navy Blue Geometric Print Georgette Sh...,0.0,0,799.0,46.0,"""₹431.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""14.8in"",""value_name"":...",NaN,"Gro███ Fl███, 4█████████n A███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [43]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
117,18962100,Nike,Women Black Brand Logo Printed Dri Fit Top,4.4,72,2495.0,NaN,"""₹2,495.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Nik███ndi███riv█████████ed,"[{""size"":""XS"",""value"":""34.25in"",""value_name"":""...","[""rw-18962100_cae700""]",Oly███a B███din█████████e T███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
118,18972666,MALHAAR,Yellow Print Wrap Top,0.0,0,3329.0,78.0,"""₹732.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,BED███E S███IES██████,"[{""size"":""XS"",""value"":""33.0in"",""value_name"":""T...",NaN,1/4███Rii███Ind█████████rea███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
119,13748756,Madame,Women Peach-Coloured Self Checked Top,3.6,35,1599.0,70.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",JAI███MAR███OTH█████████TD,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Bu...",NaN,CIN███520███200█████████0 #███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
120,22568668,V-Mart,High Neck Puff Sleeves Gathered Georgette Top,3.7,30,449.0,NaN,"""₹449.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",V-M███ Re███l L█████████,"[{""size"":""S"",""value"":""25.0in"",""value_name"":""Fr...",NaN,Plo███o.8███ Se█████████Pha███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops
121,19297208,Friskers,Women Black Solid Organic Cotton Tank Top,0.0,0,1578.0,60.0,"""₹631.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Fly███,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tops

In [44]:
df.shape

(122, 24)

In [45]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [46]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              122 non-null    int64
 1   title                   122 non-null    object
 2   product_description     122 non-null    object
 3   rating                  122 non-null    float64
 4   ratings_count           122 non-null    int64
 5   initial_price           122 non-null    float64
 6   discount                107 non-null    float64
 7   final_price             122 non-null    object
 8   currency                122 non-null    object
 9   images                  122 non-null    object
 10  delivery_options        122 non-null    object
 11  product_details         122 non-null    object
 12  breadcrumbs             122 non-null    object
 13  product_specifications  122 non-null    object
 14  amount_of_stars         122 non-null    object
 15  what_customers_said     84 non-null     object
 16  seller_name             39 non-null     object
 17  sizes                   122 non-null    object
 18  videos                  18 non-null     object
 19  seller_information      39 non-null     object
 20  variations              51 non-null     object
 21  best_offer              122 non-null    object
 22  more_offers             122 non-null    object
 23  category                122 non-null    object
dtypes: float64(3), int64(2), object(19)
memory usage: 23.0+ KB

# Checking Missing Values

In [48]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                   15
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said        38
seller_name                83
sizes                       0
videos                    104
seller_information         83
variations                 71
best_offer                  0
more_offers                 0
category                    0
dtype: int64

# Handling Missing Values

In [74]:
df['discount'] = df['discount'].fillna(0)

df['what_customers_said'] = df['what_customers_said'].fillna("No Review")

df['seller_name'] = df['seller_name'].fillna("Unknown Seller")

df['videos'] = df['videos'].fillna("No Video")

df['seller_information'] = df['seller_information'].fillna("No Information")

df['variations'] = df['variations'].fillna("No Variation")

df['variations'] = df['variations'].replace(r'^\[\{\}\]$', 'No Variation', regex=True)

# Verify Missing Values Again

In [75]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
discount_amount           0
dtype: int64

# Checking Duplicate Rows

In [76]:
df.duplicated().sum()

np.int64(0)

# Removing Duplicates

In [77]:
df = df.drop_duplicates()

# Select Specific Columns

In [78]:
print(df[['title', 'rating', 'final_price']].head())

             title  rating  final_price
0         Oxolloxo     0.0        599.0
1          MALHAAR     0.0        699.0
2  her by invictus     4.2        475.0
3          MALHAAR     0.0        732.0
4       KiddoPanti     0.0        431.0

# Filtering High Rated Products

In [79]:
high_rating = df[df['rating'] > 4]

print(high_rating[['title', 'rating', 'final_price']].head())

              title  rating  final_price
2   her by invictus     4.2        475.0
6       HILL STREET     4.5        594.0
7       Zink London     4.3        524.0
9             Levis     4.4       1133.0
11        Chemistry     4.5       1499.0

# Clean final_price Column

In [80]:
df['final_price'] = df['final_price'].replace('[₹,"]', '', regex=True)

df['final_price'] = df['final_price'].astype(float)

# Creating Derived Column

In [81]:
df['discount_amount'] = df['initial_price'] - df['final_price']

print(df[['initial_price', 'final_price', 'discount_amount']])

     initial_price  final_price  discount_amount
0           2299.0        599.0           1700.0
1           3329.0        699.0           2630.0
2           1398.0        475.0            923.0
3           3329.0        732.0           2597.0
4            799.0        431.0            368.0
..             ...          ...              ...
117         2495.0       2495.0              0.0
118         3329.0        732.0           2597.0
119         1599.0        479.0           1120.0
120          449.0        449.0              0.0
121         1578.0        631.0            947.0

[122 rows x 3 columns]

# Save Cleaned Dataset

In [82]:
df.to_csv("cleaned_tops.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Brief Summary

In this project, I worked with the tops.csv dataset using the Pandas library in Python. First, I loaded the dataset into a DataFrame and explored it using functions like head(), tail(), shape, columns, dtypes, and info() to understand the structure of the data.

After exploring the dataset, I checked for missing values using isnull().sum() and handled them using fillna() by replacing null values with meaningful text such as "No Review", "Unknown Seller", and "No Video". I also checked for duplicate rows and removed them from the dataset.

Next, I performed some basic data operations like selecting important columns and filtering products with ratings greater than 4. I then cleaned the final_price column by removing currency symbols and converting it into float datatype so it could be used for calculations.

To create a derived column, I calculated discount_amount using the initial_price and final_price columns. Finally, I saved the cleaned dataset as cleaned_tops.csv for future use and analysis.